/// Flutter icons Target
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Target
///      fonts:
///       - asset: fonts/Target.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Target {
  Target._();

  static const _kFontFam = 'Target';
  static const String? _kFontPkg = null;

  static const IconData material_symbols_target = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mingcute_target_line = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_outlet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outlet = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
